version: "3.7"

services:
  api:
    container_name: recipeapiapp
    restart: always
    build:
      context: .
      target: development
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 4000:3000
    command: npm run dev
    links:
      - mongodb
  mongodb:
    container_name: recipeappdatabase
    image: mongo
    ports:
      - "27018:27017"  